# Generated by Django 3.2.9 on 2022-12-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20221222_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='creator',
        ),
        migrations.AddField(
            model_name='book',
            name='creator_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
