# Generated by Django 3.2.9 on 2022-12-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlikes',
            name='books_count',
            field=models.IntegerField(default=0),
        ),
    ]
