# Generated by Django 3.2.9 on 2022-12-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userlikes_books_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlikes',
            name='books_count',
        ),
        migrations.RemoveField(
            model_name='userlikes',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='userlikes',
            name='likes',
        ),
        migrations.AddField(
            model_name='userlikes',
            name='liked_user',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlikes',
            name='liker_user',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
